let clase = {
  title: "Clase",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit.    Mollitia, deserunt rerum. Aspernatur, quos.",
  temas: ["Java", "script", "Front", "Back"],
  isCompleted: false,
};

export const CursoBase = {
  id: 1,
  titulo: "JavaScript",
  calificacion: 2000,
  imagen:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/800px-JavaScript-logo.png",
  userIncript: 4567,
  description:
    "JavaScript es el lenguaje de programación que debes usar para añadir características interactivas a tu sitio web, (por ejemplo, juegos, eventos que ocurren cuando los botones son presionados o los datos son introduc_idos en los formularios, efectos de estilo dinámicos, animación, y mucho más)",
  lessons: [
    {
      _id: 1,
      titulo: "Hello World!",
      descripcion: "El tipico ejercicio introductorio Hello World",
      num: 1,
      isCompleted: true,
      isLocked: false,
    },
    {
      _id: 2,
      titulo: "clase prueba",
      descripcion: "clase de prueba",
      num: 2,
      isCompleted: true,
      isLocked: false,
    },
    {
      _id: 3,
      titulo: "clase prueba",
      descripcion: "clase de prueba?",
      num: 3,
      isCompleted: true,
      isLocked: false,
    },
    // {
    //   ...clase,
    //   _id: 4,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: false,
    // },
    // {
    //   ...clase,
    //   _id: 5,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 6,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 7,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 8,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 9,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 10,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 11,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 12,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 13,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 14,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 15,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 16,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 17,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 18,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 19,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 20,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 21,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 22,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 23,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 24,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 25,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 26,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
    // {
    //   ...clase,
    //   _id: 27,
    //   titulo: "clase prueba",
    //   descripcion: "clase de prueba",
    //   isCompleted: false,
    //   isLocked: true,
    // },
  ],
};
