export const CursoBase = {
    id,
    titulo: "JavaScript",
    calificacion: 2000,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/800px-JavaScript-logo.png",
    userIncript: 4567,
    description:
      "JavaScript es el lenguaje de programación que debes usar para añadir características interactivas a tu sitio web, (por ejemplo, juegos, eventos que ocurren cuando los botones son presionados o los datos son introducidos en los formularios, efectos de estilo dinámicos, animación, y mucho más)",
    clases: [
      {
        ...clase,
        id: 1,
        titulo: "Hello World!",
        descripcion: "El tipico ejercicio introductorio Hello World",
        isCompleted: true,
        isLocked: false,
      },
      {
        ...clase,
        id: 2,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: true,
        isLocked: false,
      },
      {
        ...clase,
        id: 3,
        titulo: "clase prueba",
        descripcion: "clase de prueba?",
        isCompleted: true,
        isLocked: false,
      },
      {
        ...clase,
        id: 4,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: false,
      },
      {
        ...clase,
        id: 5,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 6,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 7,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 8,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 9,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 10,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 11,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 12,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 13,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 14,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 15,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 16,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 17,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 18,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 19,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 20,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 21,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 22,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 23,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 24,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 25,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 26,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
      {
        ...clase,
        id: 27,
        titulo: "clase prueba",
        descripcion: "clase de prueba",
        isCompleted: false,
        isLocked: true,
      },
    ],
  };