export const SET_COURSES = 'SET_COURSES';
export const SET_SHOWEDCOURSES = 'SET_SHOWEDCOURSES';
export const SET_VALIDATEUSER = "SET_VALIDATEUSER";
export const SET_THEME = "SET_THEME";
export const LOGOUT = "LOGOUT";
export const SET_UPDATEUSER = 'SET_UPDATEUSER';

// course favorite
export const BOOKMARCOURSE = 'BOOKMARCOURSE';
export const UNMARKFAVORITES = 'UNMARKFAVORITES';
