export const POST_NEW_USER = 'POST_NEW_USER';
export const SET_COURSES = 'SET_COURSES';
export const GET_COURSEBYNAME = 'GET_COURSEBYNAME';
export const SET_SHOWEDCOURSES = 'SET_SHOWEDCOURSES';
export const SET_VALIDATEUSER = "SET_VALIDATEUSER";
export const SET_THEME = "SET_THEME";
export const SET_UNVALIDATEUSER = "SET_UNVALIDATEUSER";
